var GAME_LEVELS = [
  ["                                                    x                           ",
   "           xx    xxxx xx        xx xxxx  xx       xxx                           ",
   "           xx    xx    xx      xx  xx    xx        xx                           ",
   "           xx    xxxx   xx    xx   xxxx  xx        xx                           ",
   "           xx    xx      xx  xx    xx    xx        xx                   $       ",
   "           xxxx  xxxx     xxxx     xxxx  xxxx     xxxx            o             ",
   "                                                                  xxx           ",
   "                                                   xx      x    x!!!xx          ",
   "                                    o o      xx                  x!!!x          ",
   "                                                                 x!!!x          ",
   "                                   xxxxx                         x!!!           ",
   "                                                                 x!!!  x    xx  ",
   "  x                                       o o                    x!!!!!!x    x  ",
   "  x               !!!      o                                      xxxxxxx!!x x  ",
   "  x               !!!                      xxxxx                              x ",
   "  x               !!!   %   o        $                                           ",
   "  x  @            !!!                                 !!!!!                   x ",
   "  xxxxxxxxxxx  xxxxxxxxxxxxxxxx!!!xxxxxxxxxxxxxxxxxxxx!!!!!xxxxxxx   xxxxxxxxx  ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              x!!!x                  xxxxxxx                    ",
   "                               !!!                                              ",
   "                                                                                "],
  ["                                                    x                           ",
   "           xx    xxxx xx        xx xxxx  xx      xxxx                           ",
   "           xx    xx    xx      xx  xx    xx        xxx                o         ",
   "           xx    xxxx   xx    xx   xxxx  xx       xxx                           ",
   "           xx    xx      xx  xx    xx    xx      xxx                            ",
   "           xxxx  xxxx     xxxx     xxxx  xxxx      xxxx                         ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                           xx    xx!!!!xx       ",
   "                                                                 x!!!!!!x       ",
   "                                                                 x!!!!!!x       ",
   "                                                                 x!!!!!!x       ",
   "                                                                 x!!!!!!x       ",
   "  x                                       o o      xx     $      x!!!!!!x       ",
   "  x                        o                                      !!!!!!        ",
   "  x                                                               !!!!!!        ",
   "  x                        o         $                            !!!!!!        ",
   "  x  @           $                         xxxxx                  !!!!!!        ",
   "  xxxxxxxxxxx!!!!!!xxxxx!!!xxx!!!!!xxxx!!!!!!!!!!!!!!xxx!!!!!xxxxx!!!!!!!!xxxxxx",
   "             x!!!!!!!!x               x!!!x           x!!!!!x                   ",
   "             xxxxxxxxxx               x!!!x           x!!!!!x                   ",
   "                                                      x!!!!!x                   ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                ",
   "           xx    xxxx xx        xx xxxx  xx      xxxx                           ",
   "           xx    xx    xx      xx  xx    xx        xxx                          ",
   "           xx    xxxx   xx    xx   xxxx  xx       xxx                           ",
   "           xx    xx      xx  xx    xx    xx        xxx                          ",
   "           xxxx  xxxx     xxxx     xxxx  xxxx    xxxx                           ",
   "                                                                                ",
   "                         o                                                      ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                         o                                      ",
   "  x                                      xx                                     ",
   "  x                                                                             ",
   "  x             $                    $                                          ",
   "  x                                                                             ",
   "  x  @       !!!!                                                               ",
   "  xxxxxxxxxxx!!!!!!xxx!!!!!!xxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxx",
   "  x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                "],
   ["                                                                               ",
   "          xx    xx  xxxx   xx  xx   xx       xx  xxxx  xxxx   xx                ",
   "           xx  xx  xx  xx  xx  xx   xx       xx   xx   xx xx  xx                ",
   "             xx    xx  xx  xx  xx   xx  xx   xx   xx   xx  xx xx                ",
   "             xx    xx  xx  xx  xx   xx  xx   xx   xx   xx   x xx                ",
   "             xx     xxxx    xxxx      xxx xxx    xxxx  xx   xxxx                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "     @   oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo   ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                "],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
